name: shopkg
description: A new Flutter project.

publish_to: 'none' 

# 
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # firebase
  firebase_auth: ^3.3.17
  cloud_firestore: ^3.1.14
  firebase_core: ^1.16.0
  # slider
  # flutter_carousel_slider: ^1.0.8
  carousel_slider: ^4.1.1
  # getX
  get: ^4.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  google_fonts: ^2.2.0
 
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - images/

 